/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MSQLQueryRuntimeModule extends AbstractMSQLQueryRuntimeModule {
}
