/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MSQLQueryUiModule extends AbstractMSQLQueryUiModule {

	public MSQLQueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
