/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MSQLQueryStandaloneSetup extends MSQLQueryStandaloneSetupGenerated {

	public static void doSetup() {
		new MSQLQueryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
