/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MSQLSchemaProposalProvider extends AbstractMSQLSchemaProposalProvider {
}
