/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mdse.minisql.schema.MSQLSchemaRuntimeModule;
import org.mdse.minisql.schema.MSQLSchemaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MSQLSchemaIdeSetup extends MSQLSchemaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MSQLSchemaRuntimeModule(), new MSQLSchemaIdeModule()));
	}
	
}
