/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.ide;


/**
 * Use this class to register ide components.
 */
public class MSQLSchemaIdeModule extends AbstractMSQLSchemaIdeModule {
}
