/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSchemaScopeProvider extends DelegatingScopeProvider {
}
