/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.mdse.minisql.query.AllColumnsWhatDirective;
import org.mdse.minisql.query.ColumnReference;
import org.mdse.minisql.query.FromClause;
import org.mdse.minisql.query.OrderByClause;
import org.mdse.minisql.query.OrderByDirective;
import org.mdse.minisql.query.QueryPackage;
import org.mdse.minisql.query.SelectQuery;
import org.mdse.minisql.query.SingleColumnWhatDirective;
import org.mdse.minisql.query.WhatClause;
import org.mdse.minisql.query.services.MSQLQueryGrammarAccess;

@SuppressWarnings("all")
public class MSQLQuerySemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MSQLQueryGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == QueryPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case QueryPackage.ALL_COLUMNS_WHAT_DIRECTIVE:
				sequence_AllColumnsWhatDirective(context, (AllColumnsWhatDirective) semanticObject); 
				return; 
			case QueryPackage.COLUMN_REFERENCE:
				sequence_ColumnReference(context, (ColumnReference) semanticObject); 
				return; 
			case QueryPackage.FROM_CLAUSE:
				sequence_FromClause(context, (FromClause) semanticObject); 
				return; 
			case QueryPackage.ORDER_BY_CLAUSE:
				sequence_OrderByClause(context, (OrderByClause) semanticObject); 
				return; 
			case QueryPackage.ORDER_BY_DIRECTIVE:
				sequence_OrderByDirective(context, (OrderByDirective) semanticObject); 
				return; 
			case QueryPackage.SELECT_QUERY:
				sequence_SelectQuery(context, (SelectQuery) semanticObject); 
				return; 
			case QueryPackage.SINGLE_COLUMN_WHAT_DIRECTIVE:
				sequence_SingleColumnWhatDirective(context, (SingleColumnWhatDirective) semanticObject); 
				return; 
			case QueryPackage.WHAT_CLAUSE:
				sequence_WhatClause(context, (WhatClause) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     WhatDirective returns AllColumnsWhatDirective
	 *     AllColumnsWhatDirective returns AllColumnsWhatDirective
	 *
	 * Constraint:
	 *     {AllColumnsWhatDirective}
	 */
	protected void sequence_AllColumnsWhatDirective(ISerializationContext context, AllColumnsWhatDirective semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ColumnReference returns ColumnReference
	 *
	 * Constraint:
	 *     column=[Column|ID]
	 */
	protected void sequence_ColumnReference(ISerializationContext context, ColumnReference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QueryPackage.Literals.COLUMN_REFERENCE__COLUMN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QueryPackage.Literals.COLUMN_REFERENCE__COLUMN));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColumnReferenceAccess().getColumnColumnIDTerminalRuleCall_0_1(), semanticObject.eGet(QueryPackage.Literals.COLUMN_REFERENCE__COLUMN, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     FromClause returns FromClause
	 *
	 * Constraint:
	 *     table=[Table|ID]
	 */
	protected void sequence_FromClause(ISerializationContext context, FromClause semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QueryPackage.Literals.FROM_CLAUSE__TABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QueryPackage.Literals.FROM_CLAUSE__TABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFromClauseAccess().getTableTableIDTerminalRuleCall_1_0_1(), semanticObject.eGet(QueryPackage.Literals.FROM_CLAUSE__TABLE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     OrderByClause returns OrderByClause
	 *
	 * Constraint:
	 *     (orderDirectives+=OrderByDirective orderDirectives+=OrderByDirective*)
	 */
	protected void sequence_OrderByClause(ISerializationContext context, OrderByClause semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     OrderByDirective returns OrderByDirective
	 *
	 * Constraint:
	 *     (columnReference+=ColumnReference (ascending?='ASC' | ascending?='DESC')?)
	 */
	protected void sequence_OrderByDirective(ISerializationContext context, OrderByDirective semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SelectQuery returns SelectQuery
	 *
	 * Constraint:
	 *     (whatClause+=WhatClause fromClause=FromClause orderByClause=OrderByClause?)
	 */
	protected void sequence_SelectQuery(ISerializationContext context, SelectQuery semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     WhatDirective returns SingleColumnWhatDirective
	 *     SingleColumnWhatDirective returns SingleColumnWhatDirective
	 *
	 * Constraint:
	 *     columnReference=ColumnReference
	 */
	protected void sequence_SingleColumnWhatDirective(ISerializationContext context, SingleColumnWhatDirective semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QueryPackage.Literals.SINGLE_COLUMN_WHAT_DIRECTIVE__COLUMN_REFERENCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QueryPackage.Literals.SINGLE_COLUMN_WHAT_DIRECTIVE__COLUMN_REFERENCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSingleColumnWhatDirectiveAccess().getColumnReferenceColumnReferenceParserRuleCall_0(), semanticObject.getColumnReference());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     WhatClause returns WhatClause
	 *
	 * Constraint:
	 *     (whatDirective+=WhatDirective whatDirective+=WhatDirective*)
	 */
	protected void sequence_WhatClause(ISerializationContext context, WhatClause semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
