/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MSQLSchemaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/mdse/minisql/schema/parser/antlr/internal/InternalMSQLSchema.tokens");
	}
}
