/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mdse.minisql.schema.parser.antlr.internal.InternalMSQLSchemaParser;
import org.mdse.minisql.schema.services.MSQLSchemaGrammarAccess;

public class MSQLSchemaParser extends AbstractAntlrParser {

	@Inject
	private MSQLSchemaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMSQLSchemaParser createParser(XtextTokenStream stream) {
		return new InternalMSQLSchemaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Table";
	}

	public MSQLSchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MSQLSchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
