/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mdse.minisql.schema.parser.antlr.internal.InternalSchemaParser;
import org.mdse.minisql.schema.services.SchemaGrammarAccess;

public class SchemaParser extends AbstractAntlrParser {

	@Inject
	private SchemaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSchemaParser createParser(XtextTokenStream stream) {
		return new InternalSchemaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Table";
	}

	public SchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
