/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mdse.minisql.query.parser.antlr.internal.InternalQueryParser;
import org.mdse.minisql.query.services.QueryGrammarAccess;

public class QueryParser extends AbstractAntlrParser {

	@Inject
	private QueryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQueryParser createParser(XtextTokenStream stream) {
		return new InternalQueryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SelectQuery";
	}

	public QueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
