/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.mdse.minisql.query.ide.contentassist.antlr.internal.InternalQueryParser;
import org.mdse.minisql.query.services.QueryGrammarAccess;

public class QueryParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(QueryGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, QueryGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getWhatDirectiveAccess().getAlternatives(), "rule__WhatDirective__Alternatives");
			builder.put(grammarAccess.getOrderByDirectiveAccess().getAscendingAlternatives_1_0(), "rule__OrderByDirective__AscendingAlternatives_1_0");
			builder.put(grammarAccess.getSelectQueryAccess().getGroup(), "rule__SelectQuery__Group__0");
			builder.put(grammarAccess.getWhatClauseAccess().getGroup(), "rule__WhatClause__Group__0");
			builder.put(grammarAccess.getWhatClauseAccess().getGroup_1(), "rule__WhatClause__Group_1__0");
			builder.put(grammarAccess.getAllColumnsWhatDirectiveAccess().getGroup(), "rule__AllColumnsWhatDirective__Group__0");
			builder.put(grammarAccess.getFromClauseAccess().getGroup(), "rule__FromClause__Group__0");
			builder.put(grammarAccess.getOrderByClauseAccess().getGroup(), "rule__OrderByClause__Group__0");
			builder.put(grammarAccess.getOrderByClauseAccess().getGroup_3(), "rule__OrderByClause__Group_3__0");
			builder.put(grammarAccess.getOrderByDirectiveAccess().getGroup(), "rule__OrderByDirective__Group__0");
			builder.put(grammarAccess.getSelectQueryAccess().getWhatClauseAssignment_1(), "rule__SelectQuery__WhatClauseAssignment_1");
			builder.put(grammarAccess.getSelectQueryAccess().getFromClauseAssignment_2(), "rule__SelectQuery__FromClauseAssignment_2");
			builder.put(grammarAccess.getSelectQueryAccess().getOrderByClauseAssignment_3(), "rule__SelectQuery__OrderByClauseAssignment_3");
			builder.put(grammarAccess.getWhatClauseAccess().getWhatDirectivesAssignment_0(), "rule__WhatClause__WhatDirectivesAssignment_0");
			builder.put(grammarAccess.getWhatClauseAccess().getWhatDirectivesAssignment_1_1(), "rule__WhatClause__WhatDirectivesAssignment_1_1");
			builder.put(grammarAccess.getSingleColumnWhatDirectiveAccess().getColumnReferenceAssignment(), "rule__SingleColumnWhatDirective__ColumnReferenceAssignment");
			builder.put(grammarAccess.getFromClauseAccess().getTableAssignment_1(), "rule__FromClause__TableAssignment_1");
			builder.put(grammarAccess.getOrderByClauseAccess().getOrderByDirectivesAssignment_2(), "rule__OrderByClause__OrderByDirectivesAssignment_2");
			builder.put(grammarAccess.getOrderByClauseAccess().getOrderByDirectivesAssignment_3_1(), "rule__OrderByClause__OrderByDirectivesAssignment_3_1");
			builder.put(grammarAccess.getOrderByDirectiveAccess().getColumnReferenceAssignment_0(), "rule__OrderByDirective__ColumnReferenceAssignment_0");
			builder.put(grammarAccess.getOrderByDirectiveAccess().getAscendingAssignment_1(), "rule__OrderByDirective__AscendingAssignment_1");
			builder.put(grammarAccess.getColumnReferenceAccess().getColumnAssignment(), "rule__ColumnReference__ColumnAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private QueryGrammarAccess grammarAccess;

	@Override
	protected InternalQueryParser createParser() {
		InternalQueryParser result = new InternalQueryParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public QueryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QueryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
